name: Verifica Informes 🧪
on: 
  push:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 'v20.12.2'
      
      - name: Setup Node.js
        uses: action/setup-node@v3
        with:
          node-version: 'v20.12.2'

      - name: Cypress run
        uses: cypress-io/github-action@v2